### ISSUE TITLE
Imagens com borda estão fora da borda

### ISSUE THREAD

**Issue by PedroLucasMF** [Lucianolpsf/Galeria-front-end#13]
Professor acabei de olhar aqui o site e as imagens com bordas, como a minha e a do Italo estão com a imagem menor do que a borda, provavelmente mexeram na width geral das imagens ou no padding delas.

**Comment by Lucianolpsf** [comment]
OK! Identifiquei o problema! Contribua com o projeto corrigindo este bug!

**Comment by PedroLucasMF** [comment]
já arrumei, enviei a request com o bug resolvido
